import type { MediaModel, ProviderId } from "./types";

export const PROVIDERS: { id: ProviderId; name: string }[] = [
  { id: "openai", name: "OpenAI" },
  { id: "google", name: "Google" },
  { id: "bfl", name: "Black Forest Labs" },
  { id: "ideogram", name: "Ideogram" },
  { id: "recraft", name: "Recraft" },
  { id: "xai", name: "xAI" },
  { id: "bytedance", name: "ByteDance" },
  { id: "alibaba", name: "Alibaba" },
  { id: "stability", name: "Stability AI" },
  { id: "luma", name: "Luma" },
  { id: "runway", name: "Runway" },
  { id: "kling", name: "Kling" },
  { id: "minimax", name: "MiniMax" },
  { id: "pika", name: "Pika" },
  { id: "krea", name: "Krea" },
  { id: "amazon", name: "Amazon" },
];

export const MEDIA_MODELS: MediaModel[] = [
  {
    id: "openai:gpt-image-2",
    providerId: "openai",
    provider: "OpenAI",
    name: "GPT Image 2",
    apiModel: "gpt-image-2",
    kind: "image",
    blurb: "Best default for composed retail posters. Token-billed.",
    bestFor: "Campaign heroes, complex layouts",
    envKeys: ["OPENAI_API_KEY"],
    endpoint: "https://api.openai.com/v1/images/generations",
    estimateLabel: "~$0.053 / poster",
    billing: { mode: "tokens", textInPerM: 5, imageOutPerM: 30, estOutTokens: 1650 },
  },
  {
    id: "openai:gpt-image-2-high",
    providerId: "openai",
    provider: "OpenAI",
    name: "GPT Image 2 High",
    apiModel: "gpt-image-2",
    kind: "image",
    blurb: "Same model, high quality — print lock.",
    bestFor: "Catalogue covers, print",
    envKeys: ["OPENAI_API_KEY"],
    endpoint: "https://api.openai.com/v1/images/generations",
    estimateLabel: "~$0.21 / poster",
    billing: { mode: "tokens", textInPerM: 5, imageOutPerM: 30, estOutTokens: 6800 },
  },
  {
    id: "openai:gpt-image-1-mini",
    providerId: "openai",
    provider: "OpenAI",
    name: "GPT Image 1 Mini",
    apiModel: "gpt-image-1-mini",
    kind: "image",
    blurb: "Cheap volume stills while you iterate copy.",
    bestFor: "Drafting, A/B volume",
    envKeys: ["OPENAI_API_KEY"],
    endpoint: "https://api.openai.com/v1/images/generations",
    estimateLabel: "~$0.009 / poster",
    billing: { mode: "per_image", usd: 0.009, estOutTokens: 900 },
  },
  {
    id: "google:imagen-4-fast",
    providerId: "google",
    provider: "Google",
    name: "Imagen 4 Fast",
    apiModel: "imagen-4.0-fast-generate-001",
    kind: "image",
    blurb: "Fast photoreal stills. Flat per image.",
    bestFor: "Product photography speed",
    envKeys: ["GOOGLE_AI_API_KEY"],
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-fast-generate-001:predict",
    estimateLabel: "$0.02 / poster",
    billing: { mode: "per_image", usd: 0.02, estOutTokens: 1200 },
  },
  {
    id: "google:imagen-4",
    providerId: "google",
    provider: "Google",
    name: "Imagen 4",
    apiModel: "imagen-4.0-generate-001",
    kind: "image",
    blurb: "Strong text rendering for posters with headlines.",
    bestFor: "Type-in-image, banners",
    envKeys: ["GOOGLE_AI_API_KEY"],
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict",
    estimateLabel: "$0.04 / poster",
    billing: { mode: "per_image", usd: 0.04, estOutTokens: 1400 },
  },
  {
    id: "google:imagen-4-ultra",
    providerId: "google",
    provider: "Google",
    name: "Imagen 4 Ultra",
    apiModel: "imagen-4.0-ultra-generate-001",
    kind: "image",
    blurb: "Highest Imagen still quality.",
    bestFor: "Hero product shots",
    envKeys: ["GOOGLE_AI_API_KEY"],
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-ultra-generate-001:predict",
    estimateLabel: "$0.06 / poster",
    billing: { mode: "per_image", usd: 0.06, estOutTokens: 1800 },
  },
  {
    id: "google:nano-banana-2",
    providerId: "google",
    provider: "Google",
    name: "Gemini Flash Image",
    apiModel: "gemini-3.1-flash-preview-image",
    kind: "image",
    blurb: "Gemini-native image (Nano Banana 2). Fast edits too.",
    bestFor: "Iterate + edit from a still",
    envKeys: ["GOOGLE_AI_API_KEY"],
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-preview-image:generateContent",
    estimateLabel: "~$0.08 / poster",
    billing: { mode: "per_image", usd: 0.08, estOutTokens: 2000 },
  },
  {
    id: "bfl:flux-2-klein",
    providerId: "bfl",
    provider: "Black Forest Labs",
    name: "FLUX.2 Klein",
    apiModel: "flux-2-klein",
    kind: "image",
    blurb: "Cheapest FLUX.2 — good for volume drafts.",
    bestFor: "Draft stills",
    envKeys: ["BFL_API_KEY"],
    endpoint: "https://api.bfl.ai/v1/flux-2-klein",
    estimateLabel: "$0.015 / poster",
    billing: { mode: "per_mp", usdPerMp: 0.015, megapixels: 1, estOutTokens: 800 },
  },
  {
    id: "bfl:flux-2-pro",
    providerId: "bfl",
    provider: "Black Forest Labs",
    name: "FLUX.2 Pro",
    apiModel: "flux-2-pro",
    kind: "image",
    blurb: "Photorealism and prompt adherence. Billed per megapixel.",
    bestFor: "Apparel and product photos",
    envKeys: ["BFL_API_KEY"],
    endpoint: "https://api.bfl.ai/v1/flux-2-pro",
    estimateLabel: "$0.03 / poster",
    billing: { mode: "per_mp", usdPerMp: 0.03, megapixels: 1, estOutTokens: 1100 },
  },
  {
    id: "bfl:flux-2-max",
    providerId: "bfl",
    provider: "Black Forest Labs",
    name: "FLUX.2 Max",
    apiModel: "flux-2-max",
    kind: "image",
    blurb: "Top FLUX stills.",
    bestFor: "Premium product",
    envKeys: ["BFL_API_KEY"],
    endpoint: "https://api.bfl.ai/v1/flux-2-max",
    estimateLabel: "$0.07 / poster",
    billing: { mode: "per_mp", usdPerMp: 0.07, megapixels: 1, estOutTokens: 1600 },
  },
  {
    id: "ideogram:v4-turbo",
    providerId: "ideogram",
    provider: "Ideogram",
    name: "Ideogram 4 Turbo",
    apiModel: "ideogram-v4-turbo",
    kind: "image",
    blurb: "Readable poster type, cheaper tier.",
    bestFor: "Headlines on the image",
    envKeys: ["IDEOGRAM_API_KEY"],
    endpoint: "https://api.ideogram.ai/v1/ideogram-v3/generate",
    estimateLabel: "$0.03 / poster",
    billing: { mode: "per_image", usd: 0.03, estOutTokens: 1000 },
  },
  {
    id: "ideogram:v4-quality",
    providerId: "ideogram",
    provider: "Ideogram",
    name: "Ideogram 4 Quality",
    apiModel: "ideogram-v4-quality",
    kind: "image",
    blurb: "Best-in-class typography for catalogues and signage.",
    bestFor: "Print posters, in-store",
    envKeys: ["IDEOGRAM_API_KEY"],
    endpoint: "https://api.ideogram.ai/v1/ideogram-v3/generate",
    estimateLabel: "$0.10 / poster",
    billing: { mode: "per_image", usd: 0.1, estOutTokens: 1500 },
  },
  {
    id: "recraft:v4.1",
    providerId: "recraft",
    provider: "Recraft",
    name: "Recraft V4.1",
    apiModel: "recraftv4",
    kind: "image",
    blurb: "Design-native stills; vector sibling exists.",
    bestFor: "Brand-clean layouts",
    envKeys: ["RECRAFT_API_KEY"],
    endpoint: "https://external.api.recraft.ai/v1/images/generations",
    estimateLabel: "$0.035 / poster",
    billing: { mode: "per_image", usd: 0.035, estOutTokens: 1100 },
  },
  {
    id: "xai:grok-imagine-2",
    providerId: "xai",
    provider: "xAI",
    name: "Grok Imagine 2.0",
    apiModel: "grok-imagine-image-2.0",
    kind: "image",
    blurb: "xAI stills, up to 2K.",
    bestFor: "Alternate look when others feel samey",
    envKeys: ["XAI_API_KEY"],
    endpoint: "https://api.x.ai/v1/images/generations",
    estimateLabel: "~$0.05 / poster",
    billing: { mode: "per_image", usd: 0.05, estOutTokens: 1300 },
  },
  {
    id: "bytedance:seedream-4.5",
    providerId: "bytedance",
    provider: "ByteDance",
    name: "Seedream 4.5",
    apiModel: "seedream-4.5",
    kind: "image",
    blurb: "Strong composition, competitive price.",
    bestFor: "Lifestyle stills",
    envKeys: ["ARK_API_KEY"],
    endpoint: "https://ark.ap-southeast.bytepluses.com/api/v3/images/generations",
    estimateLabel: "$0.04 / poster",
    billing: { mode: "per_image", usd: 0.04, estOutTokens: 1200 },
  },
  {
    id: "alibaba:qwen-image-3",
    providerId: "alibaba",
    provider: "Alibaba",
    name: "Qwen Image 3",
    apiModel: "qwen-image-3",
    kind: "image",
    blurb: "Qwen stills, solid on product + type.",
    bestFor: "Bilingual posters later",
    envKeys: ["DASHSCOPE_API_KEY"],
    endpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation",
    estimateLabel: "$0.03 / poster",
    billing: { mode: "per_image", usd: 0.03, estOutTokens: 1000 },
  },
  {
    id: "stability:sd3.5-large",
    providerId: "stability",
    provider: "Stability AI",
    name: "Stable Diffusion 3.5 Large",
    apiModel: "sd3.5-large",
    kind: "image",
    blurb: "Open-weight family; fine-tune later.",
    bestFor: "Custom brand LoRAs",
    envKeys: ["STABILITY_API_KEY"],
    endpoint: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
    estimateLabel: "$0.065 / poster",
    billing: { mode: "per_image", usd: 0.065, estOutTokens: 1400 },
  },
  {
    id: "luma:photon-flash",
    providerId: "luma",
    provider: "Luma",
    name: "Photon Flash",
    apiModel: "photon-flash",
    kind: "image",
    blurb: "Very cheap stills from Luma.",
    bestFor: "Volume drafts",
    envKeys: ["LUMA_API_KEY"],
    endpoint: "https://api.lumalabs.ai/dream-machine/v1/generations/image",
    estimateLabel: "$0.004 / poster",
    billing: { mode: "per_image", usd: 0.004, estOutTokens: 600 },
  },
  {
    id: "krea:v2-large",
    providerId: "krea",
    provider: "Krea",
    name: "Krea 2 Large",
    apiModel: "krea-2-large",
    kind: "image",
    blurb: "Aesthetic stills, third-party listed rate.",
    bestFor: "Moodier campaigns",
    envKeys: ["KREA_API_KEY"],
    endpoint: "https://api.krea.ai/v1/generate",
    estimateLabel: "~$0.06 / poster",
    billing: { mode: "per_image", usd: 0.06, estOutTokens: 1400 },
  },
  {
    id: "amazon:titan-v2",
    providerId: "amazon",
    provider: "Amazon",
    name: "Titan Image Generator G1 v2",
    apiModel: "amazon.titan-image-generator-v2:0",
    kind: "image",
    blurb: "Bedrock stills, cheap, AWS-native.",
    bestFor: "Enterprise AWS shops",
    envKeys: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
    endpoint: "bedrock-runtime (InvokeModel)",
    estimateLabel: "$0.008 / poster",
    billing: { mode: "per_image", usd: 0.008, estOutTokens: 700 },
  },

  {
    id: "google:veo-3.1-lite",
    providerId: "google",
    provider: "Google",
    name: "Veo 3.1 Lite",
    apiModel: "veo-3.1-lite-generate-preview",
    kind: "video",
    blurb: "Cheapest Veo. 4–8s clips.",
    bestFor: "Social volume",
    envKeys: ["GOOGLE_AI_API_KEY"],
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/veo-3.1-lite-generate-preview:predictLongRunning",
    estimateLabel: "$0.05 / s",
    billing: { mode: "per_second", usdPerSec: 0.05, estTokensPerSec: 400 },
  },
  {
    id: "google:veo-3.1-fast",
    providerId: "google",
    provider: "Google",
    name: "Veo 3.1 Fast",
    apiModel: "veo-3.1-fast-generate",
    kind: "video",
    blurb: "Default ad video. Native audio available.",
    bestFor: "Instagram / web ads",
    envKeys: ["GOOGLE_AI_API_KEY"],
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/veo-3.1-fast-generate:predictLongRunning",
    estimateLabel: "$0.12 / s",
    billing: { mode: "per_second", usdPerSec: 0.12, estTokensPerSec: 700 },
  },
  {
    id: "google:veo-3.1",
    providerId: "google",
    provider: "Google",
    name: "Veo 3.1",
    apiModel: "veo-3.1-generate",
    kind: "video",
    blurb: "Highest Veo. Dialogue-grade audio.",
    bestFor: "Hero spots",
    envKeys: ["GOOGLE_AI_API_KEY"],
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/veo-3.1-generate:predictLongRunning",
    estimateLabel: "$0.40 / s",
    billing: { mode: "per_second", usdPerSec: 0.4, estTokensPerSec: 1400 },
  },
  {
    id: "openai:sora-2",
    providerId: "openai",
    provider: "OpenAI",
    name: "Sora 2",
    apiModel: "sora-2",
    kind: "video",
    blurb: "720p. Videos API sunsets 24 Sep 2026 — do not build long-term on it.",
    bestFor: "Short cinematic still-in-motion",
    envKeys: ["OPENAI_API_KEY"],
    endpoint: "https://api.openai.com/v1/videos",
    estimateLabel: "$0.10 / s",
    billing: { mode: "per_second", usdPerSec: 0.1, estTokensPerSec: 600 },
    notes: "API sunsetting 24 Sep 2026",
  },
  {
    id: "openai:sora-2-pro",
    providerId: "openai",
    provider: "OpenAI",
    name: "Sora 2 Pro",
    apiModel: "sora-2-pro",
    kind: "video",
    blurb: "Higher fidelity Sora. Same sunset.",
    bestFor: "Premium 720p spots",
    envKeys: ["OPENAI_API_KEY"],
    endpoint: "https://api.openai.com/v1/videos",
    estimateLabel: "$0.30 / s",
    billing: { mode: "per_second", usdPerSec: 0.3, estTokensPerSec: 1100 },
    notes: "API sunsetting 24 Sep 2026",
  },
  {
    id: "runway:gen-4-turbo",
    providerId: "runway",
    provider: "Runway",
    name: "Gen-4 Turbo",
    apiModel: "gen4_turbo",
    kind: "video",
    blurb: "Fast social ads. ~$0.05/s.",
    bestFor: "Iteration",
    envKeys: ["RUNWAYML_API_SECRET"],
    endpoint: "https://api.dev.runwayml.com/v1/image_to_video",
    estimateLabel: "$0.05 / s",
    billing: { mode: "per_second", usdPerSec: 0.05, estTokensPerSec: 350 },
  },
  {
    id: "runway:gen-4.5",
    providerId: "runway",
    provider: "Runway",
    name: "Gen-4.5",
    apiModel: "gen4.5",
    kind: "video",
    blurb: "Current Runway quality tier.",
    bestFor: "Polished motion",
    envKeys: ["RUNWAYML_API_SECRET"],
    endpoint: "https://api.dev.runwayml.com/v1/image_to_video",
    estimateLabel: "$0.12 / s",
    billing: { mode: "per_second", usdPerSec: 0.12, estTokensPerSec: 650 },
  },
  {
    id: "kling:3.0",
    providerId: "kling",
    provider: "Kling",
    name: "Kling 3.0",
    apiModel: "kling-v3",
    kind: "video",
    blurb: "Native 4K path, 3–15s. Strong motion.",
    bestFor: "Product move + lifestyle",
    envKeys: ["KLING_ACCESS_KEY", "KLING_SECRET_KEY"],
    endpoint: "https://api.klingai.com/v1/videos/text2video",
    estimateLabel: "$0.10 / s",
    billing: { mode: "per_second", usdPerSec: 0.1, estTokensPerSec: 550 },
  },
  {
    id: "kling:3.0-turbo",
    providerId: "kling",
    provider: "Kling",
    name: "Kling 3.0 Turbo",
    apiModel: "kling-v3-turbo",
    kind: "video",
    blurb: "Faster Kling with native audio option.",
    bestFor: "With-audio social",
    envKeys: ["KLING_ACCESS_KEY", "KLING_SECRET_KEY"],
    endpoint: "https://api.klingai.com/v1/videos/text2video",
    estimateLabel: "$0.11 / s",
    billing: { mode: "per_second", usdPerSec: 0.11, estTokensPerSec: 600 },
  },
  {
    id: "bytedance:seedance-2-fast",
    providerId: "bytedance",
    provider: "ByteDance",
    name: "Seedance 2.0 Fast",
    apiModel: "seedance-2.0-fast",
    kind: "video",
    blurb: "Token-billed video; cheap fast tier.",
    bestFor: "High-volume cuts",
    envKeys: ["ARK_API_KEY"],
    endpoint: "https://ark.ap-southeast.bytepluses.com/api/v3/contents/generations/tasks",
    estimateLabel: "$0.05 / s",
    billing: { mode: "per_second", usdPerSec: 0.05, estTokensPerSec: 900 },
  },
  {
    id: "minimax:hailuo-2.3",
    providerId: "minimax",
    provider: "MiniMax",
    name: "Hailuo 2.3",
    apiModel: "MiniMax-Hailuo-2.3",
    kind: "video",
    blurb: "Competitive per-second social video.",
    bestFor: "Short product spots",
    envKeys: ["MINIMAX_API_KEY"],
    endpoint: "https://api.minimax.io/v1/video_generation",
    estimateLabel: "$0.05 / s",
    billing: { mode: "per_second", usdPerSec: 0.05, estTokensPerSec: 400 },
  },
  {
    id: "alibaba:wan-2.6",
    providerId: "alibaba",
    provider: "Alibaba",
    name: "Wan 2.6",
    apiModel: "wan2.6-t2v",
    kind: "video",
    blurb: "Open-leaning Alibaba video.",
    bestFor: "Budget motion",
    envKeys: ["DASHSCOPE_API_KEY"],
    endpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis",
    estimateLabel: "$0.05 / s",
    billing: { mode: "per_second", usdPerSec: 0.05, estTokensPerSec: 380 },
  },
  {
    id: "luma:ray-3",
    providerId: "luma",
    provider: "Luma",
    name: "Ray 3",
    apiModel: "ray-3",
    kind: "video",
    blurb: "Dream Machine current still-to-motion.",
    bestFor: "Poster → ad video",
    envKeys: ["LUMA_API_KEY"],
    endpoint: "https://api.lumalabs.ai/dream-machine/v1/generations",
    estimateLabel: "$0.08 / s",
    billing: { mode: "per_second", usdPerSec: 0.08, estTokensPerSec: 500 },
  },
  {
    id: "pika:2.2",
    providerId: "pika",
    provider: "Pika",
    name: "Pika 2.2",
    apiModel: "pika-2.2",
    kind: "video",
    blurb: "Playful motion, good for grocery energy.",
    bestFor: "Light, fast ads",
    envKeys: ["PIKA_API_KEY"],
    endpoint: "https://api.pika.art/v1/generate",
    estimateLabel: "$0.06 / s",
    billing: { mode: "per_second", usdPerSec: 0.06, estTokensPerSec: 420 },
  },
  {
    id: "xai:grok-video-1.5",
    providerId: "xai",
    provider: "xAI",
    name: "Grok Video 1.5",
    apiModel: "grok-video-1.5",
    kind: "video",
    blurb: "xAI motion. Preset voices if dialogue.",
    bestFor: "Alternate video look",
    envKeys: ["XAI_API_KEY"],
    endpoint: "https://api.x.ai/v1/videos/generations",
    estimateLabel: "$0.08 / s",
    billing: { mode: "per_second", usdPerSec: 0.08, estTokensPerSec: 520 },
  },
];

export const DEFAULT_IMAGE_MODEL = "openai:gpt-image-2";
export const DEFAULT_VIDEO_MODEL = "google:veo-3.1-fast";

export function getModel(id: string): MediaModel {
  const found = MEDIA_MODELS.find((m) => m.id === id);
  if (!found) throw new Error(`Unknown media model: ${id}`);
  return found;
}

export function getModelOrDefault(id: string | undefined, kind: MediaModel["kind"]) {
  return MEDIA_MODELS.find((m) => m.id === id && m.kind === kind) ?? modelsOf(kind)[0];
}

export function modelsOf(kind: MediaModel["kind"]) {
  return MEDIA_MODELS.filter((m) => m.kind === kind);
}

export function modelsByProvider(kind: MediaModel["kind"], providerId: ProviderId | "all") {
  const list = modelsOf(kind);
  if (providerId === "all") return list;
  return list.filter((m) => m.providerId === providerId);
}
